# Generated by Django 4.1.3 on 2023-03-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosaics", "0002_alter_mosaic_rect_number"),
    ]

    operations = [
        migrations.DeleteModel(name="Mosaic",),
    ]
