# Generated by Django 4.1.3 on 2023-03-02 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mosaic",
            name="rect_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
