name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13 # This is the action
        with:
          heroku_api_key: "3dd0a0a1-b1ed-463c-add8-e7d18101a022"
          heroku_app_name: "mosaic-app" #Must be unique in Heroku
          heroku_email: "pmd46b23@s.okayama-u.ac.jp"
          appdir: "mosaicback" # <- This will point to the api folder in your project